# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: brazo
  joint_model_group_pose: normal
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - link_01__link_02
    - link_02__link_03
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: l1__l2_jt_pos_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      link_01__link_02
l2__l3_jt_pos_controller:
  type: effort_controllers/JointPositionController
  joints:
    link_02__link_03
  gains:
    link_02__link_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1